### ISSUE TITLE
复现

### ISSUE THREAD

**Issue by Tangchaoq** [Ma-Xinzhi/EEG-TransNet#1]
作者您好！请问下2a，2b标签可以下载吗？

**Comment by Ma-Xinzhi** [comment]
您好，2a和2b的标签可以在Results of the BCI Competition IV中给出的链接里面找到。代码的错误应该跟数据维度有关系，建议检查一下数据处理过程中的维度变化。

**Comment by f348564110** [comment]
作者您好，请问您那边训练一个epoch需要多长时间。我这边一个epoch大概要10秒左右

**Comment by Ma-Xinzhi** [comment]
> 作者您好，请问您那边训练一个epoch需要多长时间。我这边一个epoch大概要10秒左右

您好，我训练一个epoch时间可能也差不多10秒左右。这个是正常的，因为在训练的过程中，每一个epoch都会去做一次数据增强，数据增强比较耗时，所以每一个epoch的时间稍微长一些。之所以这么做，是因为这样能够随机生成更多的数据用于训练。

**Comment by shawndocker-24** [comment]
作者好，想问下看到代码里，2a的train数据截取是从-0.5到4s，一共4.5s，1125个数据点；而测试集是1000个；
这一步是为什么呢？

**Comment by Ma-Xinzhi** [comment]
你好，代码里的数据窗口设置应该是之前做其他实验的时候给改了，是有问题的，现已更正。论文里面的描述是0到4s，后续的实验也都是基于0到4s提取的信号来进行的。

**Comment by awdaaabbc** [comment]
作者你好，首先感谢你能开源你的代码，包括你的上一篇论文的代码，写的很清晰。这篇论文我想问下作者跑完2a数据集所有受试者大约要多长时间

**Comment by Ma-Xinzhi** [comment]
你好，如果使用数据增广进行训练的话，可能跑完一个被试需要1-2小时，跑完整个2a数据集可能需要半天时间（12小时）左右

**Comment by awdaaabbc** [comment]
> 你好，如果使用数据增广进行训练的话，可能跑完一个被试需要1-2小时，跑完整个2a数据集可能需要半天时间（12小时）左右

感谢作者回复，祝作者科研旅途顺利

**Comment by awdaaabbc** [comment]
作者你好，请问代码中的epoch是2000吗，还是1000左右，我4060跑一个epoch要20s，感觉这么跑下去要三四天才能跑完，所以想问下作者epoch的数值可以减少一些吗，我看论文中超过1000左右准确率区别就不大了

**Comment by Ma-Xinzhi** [comment]
你好，可以考虑将epoch数值减小一些，准确率变化确实不是很大。

**Comment by yzk521** [comment]
作者您好，数据处理中preprocess_data_test_2a会一直报错，label = true_label['classlabel'] ，没有classlabel

**Comment by yzk521** [comment]
作者您好 您给的[High Gamma Dataset]链接下载后不能用

**Comment by peteli25** [comment]
Traceback (most recent call last):
  File "/home/pete/space/EEG-TransNet-main/train_transnet_2b.py", line 80, in <module>
    main(config)
  File "/home/pete/space/EEG-TransNet-main/train_transnet_2b.py", line 57, in main
    test_data, test_labels = load_BCI42_data(data_path, test_datafile)
  File "/home/pete/space/EEG-TransNet-main/data/data_utils.py", line 18, in load_BCI42_data
    data, label = shuffle_data(data, label)
  File "/home/pete/space/EEG-TransNet-main/data/data_utils.py", line 49, in shuffle_data
    shuffle_label = label[index]
IndexError: index 129 is out of bounds for axis 0 with size 120

**Comment by peteli25** [comment]
跑源码与论文中的结果差别很大
